apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    cluster: minikube
    app: argocd
spec:
  project: plt-cluster-resources
  source:
    repoURL: https://github.com/rezakaramad/charts
    targetRevision: main
    path: charts/argo-cd
    helm:
      values: |
        platform:
          appsFolder:
            repoURL: "https://github.com/rezakaramad/argocd-feature-branches"
            targetRevision: "main"
            path: "k8s"
          permittedRepos:
            - "https://github.com/rezakaramad/argocd-feature-branches"
            - "https://github.com/rezakaramad/charts"

  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true 

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
      jsonPointers:
        - /data/url
