apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gitops
  namespace: argocd
  labels:
    cluster: minikube
    app: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rezakaramad/charts
    targetRevision: main
    path: charts/platform-gitops
    helm:
      values: |
        platform:
          source:
            repoURL: "https://github.com/rezakaramad/argocd-feature-branches"
            targetRevision: "main"
            path: "k8s"

  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true 

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
 